<?
    global $_u, $_p;
?>
<section id="vldSectionHome" class="vld-section">
    <div class="vld-section-home container">
        <div class="row vld-header-row">
            <div class="col-sm-4 hidden-xs">
                <h4><?= PAGE_NAME; ?></h4>
            </div>
            <div class="col-sm-4">
                <h3><?= $_p->content['label']; ?></h3>
            </div>
            <div class="col-sm-4 hidden-xs">
                <h4><?= PAGE_CLAIM; ?></h4>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-1">1</div>
            <div class="col-sm-1">1</div>
            <div class="col-sm-1">1</div>
            <div class="col-sm-1">1</div>
            <div class="col-sm-1">1</div>
            <div class="col-sm-1">1</div>
            <div class="col-sm-1">1</div> 
            <div class="col-sm-1">1</div>
            <div class="col-sm-1">1</div>
            <div class="col-sm-1">1</div>
            <div class="col-sm-1">1</div>
            <div class="col-sm-1">1</div>
        </div>
        <div class="row">
            <div class="col-sm-2 vld-h-2">2</div>
            <div class="col-sm-2 vld-h-2">2</div>
            <div class="col-sm-2 vld-h-2">2</div>
            <div class="col-sm-2 vld-h-2">2</div>
            <div class="col-sm-2 vld-h-2">2</div>
            <div class="col-sm-2 vld-h-2">2</div>
        </div>
        <div class="row">
            <div class="col-sm-3 vld-h-5">3</div>
            <div class="col-sm-3 vld-h-5">3</div>
            <div class="col-sm-3 vld-h-5">3</div>
            <div class="col-sm-3 vld-h-5">3</div>
        </div>
        <div class="row">
            <div class="col-sm-4">4</div>
            <div class="col-sm-4">4</div>
            <div class="col-sm-4">4</div>
        </div>
        <div class="row">
            <div class="col-sm-5">5</div>
            <div class="col-sm-5">5</div>
            <div class="col-sm-2">2</div>
        </div>
        <div class="row">
            <div class="col-sm-6 vld-h-3">6</div>
            <div class="col-sm-6 vld-h-3">6</div>
        </div>
        <div class="row">
            <div class="col-sm-7">7</div>
            <div class="col-sm-5">5</div>
        </div>
        <div class="row">
            <div class="col-sm-8">8</div>
            <div class="col-sm-4">4</div>
        </div>
        <div class="row">
            <div class="col-sm-9">9</div>
            <div class="col-sm-3">3</div>
        </div>
        <div class="row">
            <div class="col-sm-10">10</div>
            <div class="col-sm-2">2</div>
        </div>
        <div class="row">
            <div class="col-sm-11">11</div>
            <div class="col-sm-1">1</div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="row">
                    <div class="col-xs-6">6</div>
                    <div class="col-xs-6">6</div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="row">
                    <div class="col-xs-5">5</div>
                    <div class="col-xs-7">
                        <div class="row">
                            <div class="col-xs-6 vld-h-2">6</div>
                            <div class="col-xs-6 vld-h-3">6</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="row">
                    <div class="col-xs-12 col-sm-3">3</div>
                    <div class="col-xs-12 col-sm-9">
                        <div class="row">
                            <div class="col-xs-2 vld-h-2">2</div>
                            <div class="col-xs-2 vld-h-3">2</div>
                            <div class="col-xs-2 vld-h-4">2</div>
                            <div class="col-xs-2 vld-h-5">2</div>
                            <div class="col-xs-2 vld-h-2">2</div>
                            <div class="col-xs-2 vld-h-2">2</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>