<?
global $_u, $_p;
?>
<section id="vldSectionHome" class="vld-section">
    <div class="vld-section-home">
        <div class="row">
            <div class="col-sm-4 hidden-xs"></div>
            <div class="col-sm-4">
                <h3><?= $_p->content['label']; ?></h3>
            </div>
            <div class="col-sm-4 hidden-xs"></div>
        </div>
        <div class="row">
            <div class="col-sm-2">A</div>
            <div class="col-sm-9">
                B
            </div>
            <div class="col-sm-1">C</div>
        </div>
    </div>
</section>